[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50
fileWatcherType = "none"
runOnSave = false
enableWebsocketCompression = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "full"
toolbarMode = "minimal"

[runner]
fastReruns = true
magicEnabled = false

[theme]
primaryColor = "#3069e1"
backgroundColor = "#f3f4f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#1c1c1c"
font = "sans serif"

[logger]
level = "info"
